/**
 * Injects Supabase env vars into a runtime config file for Vercel builds.
 * Reads from process.env (set in Vercel Dashboard).
 */
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const outPath = join(root, 'src', 'js', 'config', 'env.runtime.js');

const env = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
};

mkdirSync(dirname(outPath), { recursive: true });

const content = `// Auto-generated by scripts/inject-env.js — do not edit manually
window.__ENV = ${JSON.stringify(env, null, 2)};
`;

writeFileSync(outPath, content, 'utf8');
console.log('[inject-env] Wrote', outPath);
